joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 30

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - a1
    - a2
    - a3
    - a4
    - a5
    - a6
    - a7
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    a1: {trajectory: 0.1, goal: 0.1}
    a2: {trajectory: 0.1, goal: 0.1}
    a3: {trajectory: 0.1, goal: 0.1}
    a4: {trajectory: 0.1, goal: 0.1}
    a5: {trajectory: 0.1, goal: 0.1}
    a6: {trajectory: 0.1, goal: 0.1}
    a7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10